apiVersion: apps/v1
kind: Deployment
metadata:
	name: mongodb
spec:
	selector:
	app: mongodb
template:
	metadata:
		labels:
			app: mongodb
	spec:
		containers:
			- name: mongodb
			  image: mongo:4.4.6
			  ports:
			    - containerPort: 27017
			env:
				-name: "MONGODB_INITDB_ROOT_USERNAME"
				value: "mongouser"
				-name: "MONGODB_INITDB_ROOT_PASSWORD"
				value: "mongopwd"
apiVersion: v1
kind: Service
metadata:
	name: mongodb
spec: 
	selector:
		app: mongodb
spec:
	selector:	
	app: mongodb
	ports:
		-port: 27017
	type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
	name: web
spec:
	selector:
	app: web
template:
	metadata:
		labels:
			app: web
	spec:
		containers:
			- name: web
			  image: richardsonbruno/rotten-potatoes
		  	ports:
				  - containerPort: 5000
			env:
				-name: "MONGODB_DB"
				value: "admin"
				-name: "MONGODB_HOST"
				value: "mongodb"
				-name: "MONGODB_PORT"
				value: 27017
				-name: "MONGODB_USERNAME"
				value: "mongouser"
				-name: "MONGODB_HOST"
				value: "mongopwd"
apiVersion: v1
kind: Service
metadata:
	name: web
spec: 
	selector:
		app: web
spec:
	selector:	
	app: web
	ports:
		-port: 80
		 targetPort: 5000
		 nodePort: 3000
	type: NodePort
